language: node_js
node_js:
  - "10"
before_install:
- openssl aes-256-cbc -K $encrypted_45c5e8be00fb_key -iv $encrypted_45c5e8be00fb_iv -in github_deploy_key.enc -out ~/.ssh/github_deploy_key -d
- chmod 600 ~/.ssh/github_deploy_key
- eval $(ssh-agent)
- ssh-add ~/.ssh/github_deploy_key
- cp ssh_config ~/.ssh/config
- git config --global user.name 'zhroot'
- git config --global user.email '271417377@qq.com'

install:
- mkdir auto-gen
- mkdir publish
- git clone $web_gen_url ./auto-gen
- mkdir auto-gen/publish
- git clone $publish_url ./publish

before_script:
- cd ./auto-gen
- npm install

script:
- node main.js

after_success:
- cd ..
- \cp -rf ./auto-gen/publish ./publish
- cd ./publish/ 
- git add -A . 
- git commit -m 'by travis bot' 
- git push

